const menu = {
  "freshRoll": [
    {
      "name": "Albacore Lover's Roll",
      "in": "Albacore, Cucumber, Spicy Imitation Crabmeat",
      "out": "Albacore, Onion, Ponzu Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FAlbacoreLoversRoll.webp?alt=media&token=d5d02af9-d626-4105-a24c-d4f681336965",
      "pcs": "8",
      "price": "13.99"
    },
    {
      "name": "Hawaiian Roll",
      "in": "Avocado, Imitation Crabmeat",
      "out": "Tuna",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FHawaiianRoll.webp?alt=media&token=59c900e4-fbf4-4d86-b3f8-b98977d33865",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "Hot Night Roll",
      "in": "Shrimp Tempura, Imitation Crabmeat",
      "out": "Spicy Tuna, Crunch,Jalapeños ",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FHotNightRoll.webp?alt=media&token=0ae0fec6-a6e2-4b8a-bb3e-cf42cda4a30b",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Norwalk Roll",
      "in": "Steamed Shrimp, Cucumber, Spicy Imitation Crabmeat",
      "out": "Salmon",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FNorwalkRoll.webp?alt=media&token=a390e17a-ea14-44ed-95b2-ec2fb5be63c8",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Philadelphia Roll",
      "in": "Salmon, Avocado, Cream Cheese",
      "out": "Masago",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FPhiladelphiaRoll.webp?alt=media&token=676674fe-6b12-433f-b17c-e321661bbbf6",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Rainbow Roll",
      "in": "Avocado, Imitation crabmeat",
      "out": "Assorted Fish",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FRainbowRoll.webp?alt=media&token=920cfbd0-6126-4480-8cc4-02654dfcf8fb",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Spicy Tuna Roll",
      "in": "Spicy Tuna, Cucumber",
      "out": "N/A",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FSpicyTunaRoll.webp?alt=media&token=104f8c20-d4d8-4f76-a5bc-c99ebb3b2834",
      "pcs": "8",
      "price": "10.99"
    },
    {
      "name": "Tuna Lover's Roll",
      "in": "Spicy Tuna, Cucumber",
      "out": "Fresh Tuna",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FTunaLoversRoll.webp?alt=media&token=8b370dc4-dac8-47f2-9671-bad0ff5db778",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Vegetable Roll",
      "in": "Assorted Veggies",
      "out": "N/A",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FVegetableRoll.webp?alt=media&token=d3f39046-d72a-4c12-b188-42d322f0453b",
      "pcs": "5",
      "price": "8.99"
    },
    {
      "name": "Sunny Beach Roll",
      "in": "Spicy Tuna, Avocado",
      "out": "Salmon, Tuna",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FSunnyBeachRoll.webp?alt=media&token=8b78540d-ac87-4a61-9203-46b7ae4a7d11",
      "pcs": "8",
      "price": "13.99"
    },
    {
      "name": "Amber Roll",
      "in": "Avocado, Imitation crabmeat",
      "out": "Salmon",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FAmberRoll.webp?alt=media&token=26416e4d-c8cb-4823-8aac-f5f8e2c25ca9",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "Mexican Roll",
      "in": "Steamed Shrimp, Cucumber, Spicy Imitation Crabmeat",
      "out": "Masago",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FMexicanRoll.webp?alt=media&token=aa7ee1fa-f2d1-4ace-a320-412177f18be6",
      "pcs": "8",
      "price": "11.99"
    }
  ],
  "cookedRoll": [
    {
      "name": "Baked Scallop Roll",
      "in": "",
      "out": "",
      "base": "California Roll",
      "top": "Baked Scallop, Mushroom, Masago, Onion",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FBakedScallopRoll.webp?alt=media&token=2a6e6a2e-6383-4dc6-bf5b-0646f0d83605",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "California Roll",
      "in": "avocado,crab meat",
      "out": "N/A",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FCaliforniaRoll.webp?alt=media&token=068f7143-8fd4-4341-8e0d-06f2508e224d",
      "pcs": "8",
      "price": "8.99"
    },
    {
      "name": "Caterpillar Roll",
      "in": "Eel, Cucumber, Spicy Imitation Crabmeat",
      "out": "Avocado,eel sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FCaterpillarRoll.webp?alt=media&token=2cb025cd-0161-4541-8a68-abba2db07e3e",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Cerritos Roll",
      "in": "Shrimp Tempura, Imitation Crabmeat",
      "out": "Spicy Crabmeat, Crunch, Eel Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FCerritosRoll.webp?alt=media&token=d29786e3-f83e-4b6d-a10e-337c3a6bfe95",
      "pcs": "8",
      "price": "9.99"
    },
    {
      "name": "Crunch Roll",
      "in": "Shrimp Tempura, Cucumber, Imitation Crabmeat, Avocado",
      "out": "Crunch, Eel sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FCrunchRoll.webp?alt=media&token=fbcdd696-b626-4cab-9853-a40f7e49db4a",
      "pcs": "6",
      "price": "9.99"
    },
    {
      "name": "Dragon Roll",
      "in": "Shrimp Tempura, Imitation Crabmeat",
      "out": "Eel, Avocado, Eel sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FDragonRoll.webp?alt=media&token=9939fe97-5582-4d4b-bfe5-f4b9501d00c4",
      "pcs": "8",
      "price": "12.99"
    },
    {
      "name": "Eel Lover's Roll",
      "in": "Eel, Imitation Crabmeat,cucumber",
      "out": "Eel, Eel Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FEelLoversRoll.webp?alt=media&token=9df0c950-161b-4fff-a2f8-775c4b3b8dab",
      "pcs": "8",
      "price": "13.99"
    },
    {
      "name": "Dynamite Roll",
      "in": "",
      "out": "",
      "base": "Cucumber, Crabstick",
      "top": "Crawfish, Mushroom, Masago, Onion",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FDynamiteRoll.webp?alt=media&token=1692026b-7433-4a45-b3f2-675759951069",
      "pcs": "8",
      "price": "10.99"
    },
    {
      "name": "Salmon Skin Roll",
      "in": "Salmon Skin, Cucumber, Spicy Imitation Crabmeat, ",
      "out": "",
      "base": "",
      "top": "N/A",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FSalmonSkinRoll.webp?alt=media&token=b2d0550b-0787-4ed0-b953-35dd3a37444a",
      "pcs": "5",
      "price": "9.99"
    },
    {
      "name": "Scallop Lover's Roll",
      "in": "",
      "out": "",
      "base": "Cucumber, Crabstick",
      "top": "Baked Scallop, Mushroom, Masago, Onion",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FBakedScallopRoll.webp?alt=media&token=2a6e6a2e-6383-4dc6-bf5b-0646f0d83605",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "Shrimp Lover's Roll",
      "in": "Shrimp Tempura, Imitation Crabmeat",
      "out": "Steamed Shrimp, Avocado, Crunch, Eel Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FShrimpLoversRoll.webp?alt=media&token=44b660e4-3363-4a87-b599-59975e031c45",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "Spicy Tuna Tempura",
      "in": "Spicy Tuna, avocado, Imitation Crabmeat, ",
      "out": "Crunch,green onion, Eel Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FSpicyTunaTempuraRoll.webp?alt=media&token=5171a321-c01a-4a82-a6fc-4749473b3f58",
      "pcs": "8",
      "price": "11.99"
    },
    {
      "name": "Spider Roll",
      "in": "Soft Shell Crab, Imitation Crabmeat, Cucumber, Avocado",
      "out": "Crunch, Eel Sauce",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "https://firebasestorage.googleapis.com/v0/b/sushi-gallery.appspot.com/o/Rolls%2FSpiderRoll.webp?alt=media&token=fb5d1839-1109-4aa0-a49f-404e522a1f4b",
      "pcs": "6",
      "price": "12.99"
    }
  ],
  "nigiri": [
    {
      "name": "Salmon",
      "description": "2pcs with each order",
      "price": "3.99"
    },
    {
      "name": "Albacore",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Shrimp",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Spicy Scallop",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Tuna",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Yellowtail",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Escolar",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Imitation Osaki Crab",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Mackerel",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Squid",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Smelt Roe",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Salmon Roe",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Tamago (egg)",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Eel (river)",
      "description": "",
      "price": "3.99"
    },
    {
      "name": "Hamachi Toro",
      "description": "",
      "price": "5.99"
    },
    {
      "name": "Uni (1pc)",
      "description": "",
      "price": "M/P"
    }
  ],
  "sashimi": [
    {
      "name": "Tuna",
      "description": "4pcs with each order",
      "price": "6.99"
    },
    {
      "name": "Yellowtail",
      "description": "",
      "price": "7.99"
    },
    {
      "name": "Salmon",
      "description": "",
      "price": "6.99"
    },
    {
      "name": "Seared Albacore",
      "description": "",
      "price": "6.99"
    },
    {
      "name": "Escolar",
      "description": "",
      "price": "6.99"
    },
    {
      "name": "Mackerel",
      "description": "",
      "price": "7.99"
    },
    {
      "name": "Squid",
      "description": "",
      "price": "7.99"
    },
    {
      "name": "Hamachi Toro",
      "description": "",
      "price": "10.99"
    },
    {
      "name": "Uni",
      "description": "",
      "price": "M/P"
    }
  ],
  "handRoll": [
    {
      "name": "Salmon",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "2pcs with each order",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Albacore",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Shrimp",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Spicy Scallop",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Tuna",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Yellowtail",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Escolar",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Imitation Osaki Crab",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Mackerel",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Squid",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Smelt Roe",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Salmon Roe",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Tamago (egg)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Eel (river)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Hamachi Toro",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "5.99"
    },
    {
      "name": "Uni (1pc)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "M/P"
    }
  ],
  "cutRoll": [
    {
      "name": "Tuna",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "5pcs with each order",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Yellowtail",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Salmon",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Seared Albacore",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Escolar",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Shrimp",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Spicy Scallop",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Imitation Crab",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Mackerel",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Squid",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Smelt Roe",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Salmon Roe",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Tamago (egg)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Eel (river)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Hamachi Toro",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "10.99"
    },
    {
      "name": "Uni (1pc)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "M/P"
    }
  ],
  "side": [
    {
      "name": "Edamame (steamed green bean)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Spicy Garlic Edamame",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "6.99"
    },
    {
      "name": "Soft Shell Crab (deep fried)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Jalapeno Bomb (spicy tuna deep fried)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Mushroom Bomb (spicy crab deep fried)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Baked Green Mussel",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Mixed Tempura",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Calamari Tempura",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "6.99"
    },
    {
      "name": "Takoyaki (4pcs)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "6.99"
    },
    {
      "name": "Salmon Collar",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "7.99"
    },
    {
      "name": "Yellowtail Collar",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "14.99"
    },
    {
      "name": "Salmon Steak w/ Onion",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "13.99"
    },
    {
      "name": "Sashimi Sampler",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Chef's choice assortment of fish",
      "url": "",
      "pcs": "",
      "price": "22.99"
    }
  ],
  "bento": [
    {
      "name": "Bento Box A",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Pick from any 2 items and 2 sides",
      "url": "",
      "pcs": "",
      "price": "22.99"
    },
    {
      "name": "Bento Box B",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Pick from any 1 items and 2 sides",
      "url": "",
      "pcs": "",
      "price": "15.99"
    },
    {
      "name": "Items",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Sushi (6pcs) +$2.00, Sashimi (6pcs) +$2.00, Crunch Roll, Spicy Tuna Roll, California Roll, Chicken Teriyaki, Beef Bulgogi, Salmon Steak, Mixed Tempura, Mushroom Bomb",
      "url": "",
      "pcs": "",
      "price": ""
    },
    {
      "name": "Sides",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Salad, Miso Soup, Rice, Gyoza (3pcs), California Roll (4pcs), Edamame",
      "url": "",
      "pcs": "",
      "price": ""
    }
  ],
  "lunchSpecial": [
    {
      "name": "Special #1",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Cali Roll + 8pcs Spicy Tuna Roll",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Special #2",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Cali Roll + 8pcs Cerritos Roll",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Special #3",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Spicy Tuna Roll + 8pcs Cerritos Roll",
      "url": "",
      "pcs": "",
      "price": "17.99"
    },
    {
      "name": "Special #4",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Cali Roll + 4pcs Salmon Nigiri",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Special #5",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Spicy Tuna Roll + 4pcs Salmon Nigiri",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Special #6",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "8pcs Cerritos Roll + 4pcs Salmon Nigiri",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Special #7",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "4pcs Salmon Nigiri + 2pcs Tuna Nigiri + 2pcs Shrimp Nigiri + 1pc Escolar Nigiri",
      "url": "",
      "pcs": "",
      "price": "17.99"
    }
  ],
  "noodle": [
    {
      "name": "Tempura Udon",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "15.99"
    },
    {
      "name": "Chicken Udon",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "15.99"
    },
    {
      "name": "Chicken Yaki Udon (Large)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "19.99"
    }
  ],
  "sushiCombo": [
    {
      "name": "Combo A",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "7pcs of Sushi with Cali Roll (8pcs)and salad or miso soup",
      "url": "",
      "pcs": "",
      "price": "20.99"
    },
    {
      "name": "Combo B",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "7pcs of Sushi with Crunch Roll (6pcs) and salad or miso soup",
      "url": "",
      "pcs": "",
      "price": "21.99"
    },
    {
      "name": "Deluxe Sushi",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "12pcs of Assorted Sushi and salad or miso soup",
      "url": "",
      "pcs": "",
      "price": "22.99"
    }
  ],
  "salad": [
    {
      "name": "House Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.99"
    },
    {
      "name": "Seaweed Cucumber Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "13.99"
    },
    {
      "name": "Salmon Skin Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "12.99"
    },
    {
      "name": "Avocado Cucumber Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "13.99"
    },
    {
      "name": "Imitation Crab Stick Cucumber Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "13.99"
    },
    {
      "name": "Salmon Steak Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "15.99"
    },
    {
      "name": "Sashimi Salad (4 Salmon, 3 Tuna)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "16.99"
    },
    {
      "name": "Poke Salad",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "16.99"
    }
  ],
  "donburi": [
    {
      "name": "Chirashi Bowl",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "25.99"
    },
    {
      "name": "Poke Bowl",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "18.99"
    },
    {
      "name": "Unagi Bowl",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "18.99"
    }
  ],
  "partyTray": [
    {
      "name": "California Roll Tray (48pcs)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "50.00"
    },
    {
      "name": "Special Roll Tray (40pcs)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Cerritos Roll + Dragon Roll + Amber Roll + Hawaiian Roll + Norwalk Roll",
      "url": "",
      "pcs": "",
      "price": "51.00"
    },
    {
      "name": "Roll & Nigiri Tray",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Special Roll 24pcs(Amber Roll, Cerritos Roll, Dragon Roll) + Nigiri Sushi 14pcs(tuna, salmon, escolar, shrimp)",
      "url": "",
      "pcs": "",
      "price": "56.00"
    },
    {
      "name": "Nigiri Sushi Tray (35pcs)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Tuna 5pcs + Shrimp 5pcs + Yellowtail 5pcs + Albacore 5pcs + Eel 5pcs + Salmon 10pcs",
      "url": "",
      "pcs": "",
      "price": "63.00"
    }
  ],
  "beverage": [
    {
      "name": "Hot Tea*",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "2.00"
    },
    {
      "name": "Iced Tea* (Raspberry, Green Tea, Regular, Arnold Palmer, Lemonade)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "3.99"
    },
    {
      "name": "Soda (Sprite, Dr. Pepper, Coke, Coke Zero, Diet Coke)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "2.50"
    },
    {
      "name": "Hot Sake",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "8.00"
    },
    {
      "name": "Premium Junmai Cold Sake",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "15.00"
    },
    {
      "name": "Ginjo Cold Sake",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "16.00"
    },
    {
      "name": "Nigori Cold Sake (unfiltered)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "15.00"
    },
    {
      "name": "Beer (Asahi, Sapporo)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "4.00",
      "large": "8.00",
      "description": "",
      "url": "",
      "pcs": "",
      "price": ""
    }
  ],
  "dessert": [
    {
      "name": "Ice Cream",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Green Tea",
      "url": "",
      "pcs": "",
      "price": "4.50"
    },
    {
      "name": "Tempura Ice Cream",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "Green Tea",
      "url": "",
      "pcs": "",
      "price": "8.00"
    },
    {
      "name": "Red Bean Mochi (2pcs)",
      "in": "",
      "out": "",
      "base": "",
      "top": "",
      "small": "",
      "large": "",
      "description": "",
      "url": "",
      "pcs": "",
      "price": "5.00"
    }
	]
}

export default menu